### ISSUE TITLE
"/usr/share/vim/vimfiles/doc/index.cnx" doesn't exist

### ISSUE THREAD

**Issue by zhujinxuan** [cldwalker/vimdb#1]
When I run 

```
vimdb keys C-
```

An error occurss

```
E429 file "/usr/share/vim/vimfiles/doc/index.cnx" doesn't exist 
```

Vim : 7.3
ruby: 1.9.2p290
 LC_CTYPE="zh_CN.UTF-8"

**Comment by cldwalker** [comment]
It seems that vimdb can't find your index.txt. I tried recreating your issue on my mac with same ruby, vim and LC_CTYPE and am unable to.

Can you show the full backtrace of the error? What operating system do you have? Do you get the same error if you `export LC_TYPE=en_US.UTF-8`? Does `vimdb options` work? It should as it doesn't use index.txt.

**Comment by zhujinxuan** [comment]
my index.txt is in /usr/share/vim/vim73/doc/index.txt.

Get the same error when `<export LC_TYPE=en_US.UTF-8>`
`<vimdb options>` returns a error `<Could not find command "options>`

My oprating system:(Archlinux,x86_64)

```
 uname -a
 Linux myhost 3.2.9-1-ARCH #1 SMP PREEMPT Thu Mar 1 09:31:13 CET 2012 x86_64 Intel(R) Core(TM) i3 CPU 550 @ 3.20GHz GenuineIntel GNU/Linux
```

Full backtrace(Sorry I might misundestood the word "backstrace")

```
 /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/vimdb-0.4.0/lib/vimdb/keys.rb:65:in `parse_index_file': undefined method `each' for nil:NilClass (NoMethodError)
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/vimdb-0.4.0/lib/vimdb/keys.rb:14:in `create'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/vimdb-0.4.0/lib/vimdb/user.rb:10:in `items'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/vimdb-0.4.0/lib/vimdb/user.rb:14:in `search'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/vimdb-0.4.0/lib/vimdb/runner.rb:49:in `search_item'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/vimdb-0.4.0/lib/vimdb/runner.rb:24:in `keys'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/runner_library.rb:12:in `block (3 levels) in delegate_runner_methods'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/scientist.rb:87:in `call'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/scientist.rb:87:in `block (2 levels) in redefine_command_block'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/scientist.rb:123:in `call'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/scientist.rb:123:in `call_original_command'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/scientist.rb:115:in `during_analyze'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/scientist.rb:107:in `analyze'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/scientist.rb:86:in `block in redefine_command_block'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson.rb:79:in `full_invoke'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/bare_runner.rb:42:in `execute_command'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/runner.rb:31:in `execute_command'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/boson-1.0.1/lib/boson/runner.rb:26:in `start'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/gems/vimdb-0.4.0/bin/vimdb:4:in `<top (required)>'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/bin/vimdb:19:in `load'
    from /home/lenovo/.rvm/gems/ruby-1.9.2-p290/bin/vimdb:19:in `<main>'
```

**Comment by mattn** [comment]
Probably it will be fixed with #4

**Comment by mattn** [comment]
Sorry s/#2/#4/

**Comment by cldwalker** [comment]
If you want english documentation, try fix suggested in e64cd040f9e12ca87abe359a8f0ff7f20ef10859. In #4, mattn was able to get japanese to work by install japanese help files. Perhaps try install chinese help files?

**Comment by mattn** [comment]
#4 enforce to open index.txt instead of index.cnx . it specify `-N -u NONE`.  lib/vimdb/*.rb specify searching pattern in english text. So it won't work correcty even if it could open index.cnx.

**Comment by zhujinxuan** [comment]
[e64cd04](https://github.com/cldwalker/vimdb/commit/e64cd040f9e12ca87abe359a8f0ff7f20ef10859) works.

Thanks a lot for both cldwalker's program and maiin's fix.

**Comment by cldwalker** [comment]
@zhujinxuan Does the latest vimdb 0.5.1 work for you?

**Comment by zhujinxuan** [comment]
Sorry I forgot to replay.
Vimdb 0.5.1 works well

**Comment by cldwalker** [comment]
Awesome! Closing

**Comment by mattn** [comment]
cool
